chg: Adding ability to add admithub chat embed. Resolves #705.
CuBoulder/express_mono pull request #706
Opened 2020-09-16 21:47 UTC by kevincrafts

License ID: 787de579c4784176b

2020-09-23 21:30 UTC, cathysnider requested changes
To do:

- [ ] Update descriptive text on admin/settings to include AdmitHub
- [ ] Update descriptive text on /admin/settings/livechat/configuration to include text specific to AdmitHub 
- [ ] Update text that appears on admin/structure/context page to include AdmitHub

![liveChatAdmitHub](https://user-images.githubusercontent.com/638275/94071775-b707c580-fdb1-11ea-8bae-06cf9c13ea2f.jpg)

2020-09-29 19:16 UTC, AlanBCole approved these changes

2020-09-30 15:31 UTC, jwfuller commented
New requirements have emerged, closing this PR

2020-09-30 15:31 UTC, closed without merging

2020-09-30 17:41 UTC, cathysnider reviewed
Issue Closed