Feature/751 Update TravisCI build scripts with new drush location
CuBoulder/express_mono pull request #752
Opened 2020-10-28 19:26 UTC by cathysnider

2020-10-28 19:53 UTC, kevincrafts approved these changes

2020-10-28 20:10 UTC, jwfuller requested changes
Since we are using this value 20+ times, I think we should look for ways to consolidate or reduce. Does the `PATH` export in `tests/travis-ci/install.sh` allow us to call it without the full path? If not, would look at setting a variable in `.travis.yml` that all the scripts can use.

2020-10-28 20:10 UTC, jwfuller commented on tests/travis-ci/install.sh
> +export PATH="$HOME/./config/composer/vendor/bin:$PATH"
I think there is an extra `/` here

2020-10-29 14:59 UTC, jwfuller approved these changes
Approving as this fixes testing, which is very needed. I created https://github.com/CuBoulder/express_mono/issues/755 as a follow up.

2020-10-29 14:59 UTC, merged