Avoiding collisions between warnings and person image
CuBoulder/express_mono pull request #769
Opened 2020-11-19 22:02 UTC by AlanBCole

The warning messages should no longer collide. On screens larger than 786px the person photo should be on the right side of the screen, as it was before. On Screens smaller than 786px the person photo should appear in its own line above all the other person info.

## Summary of work in this PR:
- removed float property from person image
- slightly reorganized node--person.tpl.php template
    1. wrapped almost everything in a div.row.person-container
    1. put person image (img tag) into its own div.person-photo with bootstrap column widths for responsiveness
    1. put all other person info into another div.person-info with bootstrap column widths for responsiveness
- changes to people_content_type.scss
    1. .person-container class on screens wider than 786px (bootstrap's sm size and larger) has `flex-direction: row-reverse;` (to take advantage of bootstrap's .row class being set to `display:flex;`) to keep person image on right side of screen.
    1. .person-container class on screens narrower than 786px (bootstrap's xs screen size) `flex-direction: column;` (to take advantage of bootstrap's .row class being set to `display:flex;`) to display everything as column with person image on top.
    1. removed previous media queries relating to the `.person-photo img.image-*` and replaced with simple styling of `width: 100%; height: auto;` so that this image's width is now set by its parent div.person-photo via the bootstrap column widths.

2020-11-19 22:47 UTC, kevincrafts requested changes
This change in adding the rows will cause the content not to wrap underneath the photo which I think we will get some complaints on.

2020-11-20 16:32 UTC, AlanBCole commented
@kevincrafts Could you, or anyone show an example of how users expect text to wrap underneath the photo?

2020-11-20 19:57 UTC, cathysnider requested changes
On wider windows, the message "no results for this person" appears fairly far down on the screen, even below the fold, such that it can' be seen without scrolling down, which makes it seem like there is no result returned at all. It would be better if the content could appear higher up on the page.

2020-11-25 17:45 UTC, AlanBCole commented
@cathysnider Isn't that dependent on which region in which a user places the faculty publications block?

2020-11-30 20:51 UTC, kevincrafts commented
I'm still getting a collisions issue... 
![image](https://user-images.githubusercontent.com/349713/100663162-25698680-3313-11eb-8c4d-fb0ba0bd0e03.png)

2020-11-30 21:17 UTC, cathysnider requested changes
All the publications content, not just the warning message, is pushed down below the graphic, which creates a large empty spot and 
<img width="785" alt="Screen Shot 2020-11-30 at 2 16 53 PM" src="https://user-images.githubusercontent.com/638275/100666737-b726c300-3316-11eb-8822-864baf4375bf.png">
looks odd.

2020-12-01 19:59 UTC, AlanBCole commented
I have taken slightly different approach again. The issue is that the the content of the block is either the warning/error message or a list of publications. To make it so that the messages display nicely leads to the potential empty area of whitespace @cathysnider mentioned. So what I have done to try to satisfy both possible kinds of content for the person page is to add a `style:"float: left;"` attribute to the warning/error messages and to remove the bottom borders from the individual publications in a list (which also overlapped a person image), by removing the css class 'border-bottom' from faculty-publications.tpl.

I should say also that the colliding, so to speak, of faculty publications block and person image seems, to me atleast, to happen only when the block is placed in the 'below content' region of the person page.

2020-12-02 18:36 UTC, cathysnider approved these changes

2020-12-02 21:21 UTC, kevincrafts requested changes
I saw that many of our other error and status messages end with a period so this one should too.

2020-12-02 23:45 UTC, AlanBCole commented
Good catch on the punctuation!

2020-12-03 15:05 UTC, kevincrafts approved these changes

2020-12-03 17:23 UTC, merged